from NETWORK import SCANNER_ADDRESS


SERVER_CONNECTION_LOOP_TIME = 5

VISUALISER_ADDRESSES_FILE = "visualiser_addresses.txt"
SCAN_FILE_SETTINGS = "start-scan-preview.json"

URL_SCANNER_API = f"{SCANNER_ADDRESS}:8888/lswebapi"
# URL_SCANNER_SERVICE = f"{SCANNER_ADDRESS}/LS-webservice"

CHUNK_SIZE = 4_096

REQUEST_TIMEOUT = 5
UPDATE_SCANNER_LOOP_TIME = 5
UPDATE_CURRENT_JOB_LOOP_TIME = 0.2
