# Path to the ConverterFlsToLas.exe executable file
CONVERTER_FLS_TO_LAS_PATH = "path\\to\\ConverterFlsToLas.exe"


# --- CONVERTER --- #

SERVER_CONNECTION_LOOP_TIME = 5

SCANS_TMP_DIR = "scans\\tmp"
SCANS_CONVERTED_DIR = "scans\\converted"

SCAN_CONVERTED_EXTENSION = ".las"

COMMAND_CONVERTER_FLS_TO_LAS = CONVERTER_FLS_TO_LAS_PATH + " \"{scan_path}\" \"{scan_converted_dir}\""


# --- LAS --- #

LAS_HEADER_SIZE = 179
LAS_HEADER_ID_START = 104
LAS_HEADER_ID_END = 105
LAS_HEADER_POINTS_START = 107
LAS_HEADER_POINTS_END = 111
LAS_HEADER_SCALE_X_START = 131
LAS_HEADER_SCALE_X_END = 139
LAS_HEADER_SCALE_Y_START = 139
LAS_HEADER_SCALE_Y_END = 147
LAS_HEADER_SCALE_Z_START = 147
LAS_HEADER_SCALE_Z_END = 155
LAS_HEADER_OFFSET_X_START = 155
LAS_HEADER_OFFSET_X_END = 163
LAS_HEADER_OFFSET_Y_START = 163
LAS_HEADER_OFFSET_Y_END = 171
LAS_HEADER_OFFSET_Z_START = 171
LAS_HEADER_OFFSET_Z_END = 179
LAS_HEADER_OFFSET_TO_POINTS_START = 96
LAS_HEADER_OFFSET_TO_POINTS_END = 100

LAS_POINT_POSITION_X_START = 0
LAS_POINT_POSITION_X_END = 4
LAS_POINT_POSITION_Y_START = 4
LAS_POINT_POSITION_Y_END = 8
LAS_POINT_POSITION_Z_START = 8
LAS_POINT_POSITION_Z_END = 12

LAS_POINT_0_SIZE = 20
LAS_POINT_0_COLORS_START = 13
LAS_POINT_0_COLORS_END = 14

LAS_POINT_2_SIZE = 26
LAS_POINT_2_COLOR_R_START = 21
LAS_POINT_2_COLOR_R_END = 22
LAS_POINT_2_COLOR_G_START = 23
LAS_POINT_2_COLOR_G_END = 24
LAS_POINT_2_COLOR_B_START = 25
LAS_POINT_2_COLOR_B_END = 26


# --- VERTEX BUFFER --- #

# 16 bytes
#   - position  :   3 float32 x, y, z
#   - colors    :   3 int8 r, g, b
#   - 1 useless :   unity VertexBuffer must be multiple of 4
VERTEX_BUFFER_SIZE = 16
VERTEX_BUFFER_ALIGNMENT_START = 15
VERTEX_BUFFER_ALIGNMENT_END = 16
VERTEX_BUFFER_X_START = 0
VERTEX_BUFFER_X_END = 4
VERTEX_BUFFER_Y_START = 4
VERTEX_BUFFER_Y_END = 8
VERTEX_BUFFER_Z_START = 8
VERTEX_BUFFER_Z_END = 12
VERTEX_BUFFER_COLORS_START = 12
VERTEX_BUFFER_COLORS_END = 15


# --- WEBSOCKET --- #

REQUEST_TIMEOUT = 5

MESSAGE_SIZE = 4_096
